image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base
- pip install docker-compose

build:
  stage: build
  script:
  - docker-compose -f docker-compose.yml build

deploy: 
  stage: deploy
  script:
  - docker-compose -f docker-compose.yml up -d

test:
  stage: test
  script:
  - docker-compose -f docker-compose.yml run --no-deps --rm -e ENV=UNIT imagedock 
  - ./test.sh
